### PR TITLE
Allow XmlFileLoader to support service_defaults

### PR DESCRIPTION
**Pull request by ogizanagi**
Continues https://github.com/symfony/symfony/pull/21071

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
I drafted this meanwhile:
```xml
<?xml version="1.0" encoding="utf-8"?>
<container xmlns="http://symfony.com/schema/dic/services" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">
    <services>
        <defaults public="false">
            <autowire>__construct</autowire>
            <tag name="foo"/>
        </defaults>
    </services>
</container>
```

WDYT?

**Comment by nicolas-grekas** [comment]
thanks for the PR btw!

**Comment by ogizanagi** [comment]
Sure! I'll update the PR once we have a consensus on https://github.com/symfony/symfony/pull/21071 about the name and add the `autowire` element.

**Comment by nicolas-grekas** [comment]
We have the consensus, let's go :)

**Comment by ogizanagi** [comment]
Done.

It seems autowired method are not inherited from a parent definition in the `ResolveDefinitionTemplatesPass`.
Thus, I applied a fix similar to the handling of default tags on the `YamlFileLoader` in last commit.

**Comment by nicolas-grekas** [comment]
I spotted the same, which is what triggered https://github.com/symfony/symfony/pull/21072
And I'm working on https://github.com/nicolas-grekas/symfony/tree/di-inherit-tags also on the topic.
Thus I guess you should not deal with that in this PR.

**Comment by ogizanagi** [comment]
Nice. I'll remove the last commit then.

About tags, i'm still not sure I should handle it or not in this PR if your feature is merged. The tag inheritance will be opt-in, but I'd expect the default tags to be added on any definition, regardless of this new `inherit-tags` flag (inheritance isn't directly involved). WDYT?

**Comment by nicolas-grekas** [comment]
> inheritance isn't directly involved

inheritance is enabled for Definition, but disabled for ChildDefinition.
this matches the current behavior for ChildDefinition, and applies default tags to regular definitions.
That's what my linked branche does. Just needs a few tests now.

**Comment by nicolas-grekas** [comment]
Thank you @ogizanagi !

**Pull request closed without merging**
